In [4]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [4]:
import webbrowser
website = 'https://en.wikipedia.org/wiki/List_of_all-time_NFL_win-loss_records'
webbrowser.open(website)

True

In [28]:
nfl_frame = pd.read_clipboard()

In [29]:
nfl_frame

   Rank    Team       GP  Won  Lost  Tied  Pct.  First   NFL Season Division
0     1  Dallas  Cowboys  961   547   408     6  0.572  1960    NFC     East

In [30]:
nfl_frame.columns

Index([u'Rank', u'Team', u'GP', u'Won', u'Lost', u'Tied', u'Pct.', u'First',
       u'NFL', u'Season', u'Division'],
      dtype='object')

In [31]:
nfl_frame.Team

0    Dallas
Name: Team, dtype: object

In [33]:
nfl_frame['NFL']

0    1960
Name: NFL, dtype: int64

In [46]:
DataFrame(nfl_frame,columns=['Team','GP','NFL'])

     Team       GP   NFL
0  Dallas  Cowboys  1960

In [47]:
DataFrame(nfl_frame,columns=['Team','GP','NFL','Stadium'])

     Team       GP   NFL  Stadium
0  Dallas  Cowboys  1960      NaN

In [41]:
nfl_frame2 = pd.read_clipboard()

In [44]:
nfl_frame2

,Rank,Team,GP,Won,Lost,Tied,Pct.,Season,Division
0,1,Dallas Cowboys,898,512,380,6,0.573,1960,NFC East
1,2,Chicago Bears,"1,386",761,583,42,0.564,1920,NFC North
2,3,Green Bay Packers,"1,352",743,571,38,0.564,1921,NFC North
3,4,New England Patriots[b],900,500,391,9,0.561,1960,AFC East
4,5,Miami Dolphins,816,452,360,4,0.556,1966,AFC East
5,6,Minnesota Vikings,886,478,397,11,0.546,1961,NFC North
6,7,Baltimore Ravens,368,200,167,1,0.545,1996,AFC North
7,8,New York Giants,"1,321",692,596,33,0.536,1925,NFC East
8,9,Denver Broncos,900,476,414,10,0.534,1960,AFC West
9,10,San Francisco 49ers,"1,018",532,472,14,0.529,1950,NFC West
10,11,Indianapolis Colts[c],982,516,459,7,0.529,1953,AFC South
11,12,Pittsburgh Steelers,"1,208",628,558,22,0.529,1933,AFC North
12,13,Kansas City Chiefs,900,469,419,12,0.528,1960,AFC West
13,14,Oakland Raiders,900,466,423,11,0.524,1960,AFC West
14,15,Seattle Seahawks,676,344,331,1,0.510,1976,NFC West
15,16,Washington Redskins,"1,218",600,590,28,0.504,1932,NFC East
16,17,Los Angeles Chargers[d],900,447,442,11,0.503,1960,AFC West
17,18,Los Angeles Rams,"1,151",568,562,21,0.503,1937,NFC West
18,19,Carolina Panthers,384,190,193,1,0.496,1995,NFC South
19,20,Philadelphia Eagles,"1,204",577,601,26,0.490,1933,NFC East
20,21,Cleveland Browns,970,469,490,11,0.489,1950,AFC North
21,22,Tennessee Titans,900,431,463,6,0.482,1960,AFC South
22,23,Buffalo Bills,900,415,477,8,0.466,1960,AFC East
23,24,Detroit Lions,"1,249",559,658,32,0.460,1930,NFC North
24,25,Cincinnati Bengals,788,357,427,4,0.456,1968,AFC North
25,26,New Orleans Saints,802,362,435,5,0.454,1967,NFC South
26,27,New York Jets,900,401,491,8,0.450,1960,AFC East
27,28,Houston Texans,272,121,151,0,0.445,2002,AFC South
28,29,Jacksonville Jaguars,384,170,214,0,0.443,1995,AFC South
29,30,Atlanta Falcons,816,358,452,6,0.442,1966,NFC South
30,31,Arizona Cardinals,"1,346",553,753,40,0.426,1920,NFC West
31,32,Tampa Bay Buccaneers,676,260,415,1,0.385,1976,NFC South

In [48]:
DataFrame(nfl_frame2,columns=['Team','GP','Season','Division'])

                       Team     GP  Season   Division
0            Dallas Cowboys    898    1960   NFC East
1             Chicago Bears  1,386    1920  NFC North
2         Green Bay Packers  1,352    1921  NFC North
3   New England Patriots[b]    900    1960   AFC East
4            Miami Dolphins    816    1966   AFC East
5         Minnesota Vikings    886    1961  NFC North
6          Baltimore Ravens    368    1996  AFC North
7           New York Giants  1,321    1925   NFC East
8            Denver Broncos    900    1960   AFC West
9       San Francisco 49ers  1,018    1950   NFC West
10    Indianapolis Colts[c]    982    1953  AFC South
11      Pittsburgh Steelers  1,208    1933  AFC North
12       Kansas City Chiefs    900    1960   AFC West
13          Oakland Raiders    900    1960   AFC West
14         Seattle Seahawks    676    1976   NFC West
15      Washington Redskins  1,218    1932   NFC East
16  Los Angeles Chargers[d]    900    1960   AFC West
17         Los Angeles Rams  1,151    1937   NFC West
18        Carolina Panthers    384    1995  NFC South
19      Philadelphia Eagles  1,204    1933   NFC East
20         Cleveland Browns    970    1950  AFC North
21         Tennessee Titans    900    1960  AFC South
22            Buffalo Bills    900    1960   AFC East
23            Detroit Lions  1,249    1930  NFC North
24       Cincinnati Bengals    788    1968  AFC North
25       New Orleans Saints    802    1967  NFC South
26            New York Jets    900    1960   AFC East
27           Houston Texans    272    2002  AFC South
28     Jacksonville Jaguars    384    1995  AFC South
29          Atlanta Falcons    816    1966  NFC South
30        Arizona Cardinals  1,346    1920   NFC West
31     Tampa Bay Buccaneers    676    1976  NFC South

In [50]:
nfl_frame2.head()

,Rank,Team,GP,Won,Lost,Tied,Pct.,Season,Division
0,1,Dallas Cowboys,898,512,380,6,0.573,1960,NFC East
1,2,Chicago Bears,"1,386",761,583,42,0.564,1920,NFC North
2,3,Green Bay Packers,"1,352",743,571,38,0.564,1921,NFC North
3,4,New England Patriots[b],900,500,391,9,0.561,1960,AFC East
4,5,Miami Dolphins,816,452,360,4,0.556,1966,AFC East

In [51]:
nfl_frame2.tail()

,Rank,Team,GP,Won,Lost,Tied,Pct.,Season,Division
27,28,Houston Texans,272,121,151,0,0.445,2002,AFC South
28,29,Jacksonville Jaguars,384,170,214,0,0.443,1995,AFC South
29,30,Atlanta Falcons,816,358,452,6,0.442,1966,NFC South
30,31,Arizona Cardinals,"1,346",553,753,40,0.426,1920,NFC West
31,32,Tampa Bay Buccaneers,676,260,415,1,0.385,1976,NFC South

In [54]:
nfl_frame2.iloc[3]

Rank                              4
Team        New England Patriots[b]
GP                              900
Won                             500
Lost                            391
Tied                              9
Pct.                          0.561
Season                         1960
Division                   AFC East
Name: 3, dtype: object

In [56]:
nfl_frame2['Stadium'] = "Levis Stadium"

In [57]:
nfl_frame2

,Rank,Team,GP,Won,Lost,Tied,Pct.,Season,Division,Stadium
0,1,Dallas Cowboys,898,512,380,6,0.573,1960,NFC East,Levis Stadium
1,2,Chicago Bears,"1,386",761,583,42,0.564,1920,NFC North,Levis Stadium
2,3,Green Bay Packers,"1,352",743,571,38,0.564,1921,NFC North,Levis Stadium
3,4,New England Patriots[b],900,500,391,9,0.561,1960,AFC East,Levis Stadium
4,5,Miami Dolphins,816,452,360,4,0.556,1966,AFC East,Levis Stadium
5,6,Minnesota Vikings,886,478,397,11,0.546,1961,NFC North,Levis Stadium
6,7,Baltimore Ravens,368,200,167,1,0.545,1996,AFC North,Levis Stadium
7,8,New York Giants,"1,321",692,596,33,0.536,1925,NFC East,Levis Stadium
8,9,Denver Broncos,900,476,414,10,0.534,1960,AFC West,Levis Stadium
9,10,San Francisco 49ers,"1,018",532,472,14,0.529,1950,NFC West,Levis Stadium
10,11,Indianapolis Colts[c],982,516,459,7,0.529,1953,AFC South,Levis Stadium
11,12,Pittsburgh Steelers,"1,208",628,558,22,0.529,1933,AFC North,Levis Stadium
12,13,Kansas City Chiefs,900,469,419,12,0.528,1960,AFC West,Levis Stadium
13,14,Oakland Raiders,900,466,423,11,0.524,1960,AFC West,Levis Stadium
14,15,Seattle Seahawks,676,344,331,1,0.510,1976,NFC West,Levis Stadium
15,16,Washington Redskins,"1,218",600,590,28,0.504,1932,NFC East,Levis Stadium
16,17,Los Angeles Chargers[d],900,447,442,11,0.503,1960,AFC West,Levis Stadium
17,18,Los Angeles Rams,"1,151",568,562,21,0.503,1937,NFC West,Levis Stadium
18,19,Carolina Panthers,384,190,193,1,0.496,1995,NFC South,Levis Stadium
19,20,Philadelphia Eagles,"1,204",577,601,26,0.490,1933,NFC East,Levis Stadium
20,21,Cleveland Browns,970,469,490,11,0.489,1950,AFC North,Levis Stadium
21,22,Tennessee Titans,900,431,463,6,0.482,1960,AFC South,Levis Stadium
22,23,Buffalo Bills,900,415,477,8,0.466,1960,AFC East,Levis Stadium
23,24,Detroit Lions,"1,249",559,658,32,0.460,1930,NFC North,Levis Stadium
24,25,Cincinnati Bengals,788,357,427,4,0.456,1968,AFC North,Levis Stadium
25,26,New Orleans Saints,802,362,435,5,0.454,1967,NFC South,Levis Stadium
26,27,New York Jets,900,401,491,8,0.450,1960,AFC East,Levis Stadium
27,28,Houston Texans,272,121,151,0,0.445,2002,AFC South,Levis Stadium
28,29,Jacksonville Jaguars,384,170,214,0,0.443,1995,AFC South,Levis Stadium
29,30,Atlanta Falcons,816,358,452,6,0.442,1966,NFC South,Levis Stadium
30,31,Arizona Cardinals,"1,346",553,753,40,0.426,1920,NFC West,Levis Stadium
31,32,Tampa Bay Buccaneers,676,260,415,1,0.385,1976,NFC South,Levis Stadium

In [58]:
nfl_frame2['Stadium']=np.arange(32)

In [59]:
nfl_frame2

,Rank,Team,GP,Won,Lost,Tied,Pct.,Season,Division,Stadium
0,1,Dallas Cowboys,898,512,380,6,0.573,1960,NFC East,0
1,2,Chicago Bears,"1,386",761,583,42,0.564,1920,NFC North,1
2,3,Green Bay Packers,"1,352",743,571,38,0.564,1921,NFC North,2
3,4,New England Patriots[b],900,500,391,9,0.561,1960,AFC East,3
4,5,Miami Dolphins,816,452,360,4,0.556,1966,AFC East,4
5,6,Minnesota Vikings,886,478,397,11,0.546,1961,NFC North,5
6,7,Baltimore Ravens,368,200,167,1,0.545,1996,AFC North,6
7,8,New York Giants,"1,321",692,596,33,0.536,1925,NFC East,7
8,9,Denver Broncos,900,476,414,10,0.534,1960,AFC West,8
9,10,San Francisco 49ers,"1,018",532,472,14,0.529,1950,NFC West,9
10,11,Indianapolis Colts[c],982,516,459,7,0.529,1953,AFC South,10
11,12,Pittsburgh Steelers,"1,208",628,558,22,0.529,1933,AFC North,11
12,13,Kansas City Chiefs,900,469,419,12,0.528,1960,AFC West,12
13,14,Oakland Raiders,900,466,423,11,0.524,1960,AFC West,13
14,15,Seattle Seahawks,676,344,331,1,0.510,1976,NFC West,14
15,16,Washington Redskins,"1,218",600,590,28,0.504,1932,NFC East,15
16,17,Los Angeles Chargers[d],900,447,442,11,0.503,1960,AFC West,16
17,18,Los Angeles Rams,"1,151",568,562,21,0.503,1937,NFC West,17
18,19,Carolina Panthers,384,190,193,1,0.496,1995,NFC South,18
19,20,Philadelphia Eagles,"1,204",577,601,26,0.490,1933,NFC East,19
20,21,Cleveland Browns,970,469,490,11,0.489,1950,AFC North,20
21,22,Tennessee Titans,900,431,463,6,0.482,1960,AFC South,21
22,23,Buffalo Bills,900,415,477,8,0.466,1960,AFC East,22
23,24,Detroit Lions,"1,249",559,658,32,0.460,1930,NFC North,23
24,25,Cincinnati Bengals,788,357,427,4,0.456,1968,AFC North,24
25,26,New Orleans Saints,802,362,435,5,0.454,1967,NFC South,25
26,27,New York Jets,900,401,491,8,0.450,1960,AFC East,26
27,28,Houston Texans,272,121,151,0,0.445,2002,AFC South,27
28,29,Jacksonville Jaguars,384,170,214,0,0.443,1995,AFC South,28
29,30,Atlanta Falcons,816,358,452,6,0.442,1966,NFC South,29
30,31,Arizona Cardinals,"1,346",553,753,40,0.426,1920,NFC West,30
31,32,Tampa Bay Buccaneers,676,260,415,1,0.385,1976,NFC South,31

In [61]:
stadiums = Series(["Levis","AT&T"],index=[4,0])

In [62]:
stadiums

4    Levis
0     AT&T
dtype: object

In [63]:
nfl_frame2['Stadiums'] = stadiums

In [64]:
nfl_frame2

,Rank,Team,GP,Won,Lost,Tied,Pct.,Season,Division,Stadium,Stadiums
0,1,Dallas Cowboys,898,512,380,6,0.573,1960,NFC East,0,AT&T
1,2,Chicago Bears,"1,386",761,583,42,0.564,1920,NFC North,1,NaN
2,3,Green Bay Packers,"1,352",743,571,38,0.564,1921,NFC North,2,NaN
3,4,New England Patriots[b],900,500,391,9,0.561,1960,AFC East,3,NaN
4,5,Miami Dolphins,816,452,360,4,0.556,1966,AFC East,4,Levis
5,6,Minnesota Vikings,886,478,397,11,0.546,1961,NFC North,5,NaN
6,7,Baltimore Ravens,368,200,167,1,0.545,1996,AFC North,6,NaN
7,8,New York Giants,"1,321",692,596,33,0.536,1925,NFC East,7,NaN
8,9,Denver Broncos,900,476,414,10,0.534,1960,AFC West,8,NaN
9,10,San Francisco 49ers,"1,018",532,472,14,0.529,1950,NFC West,9,NaN
10,11,Indianapolis Colts[c],982,516,459,7,0.529,1953,AFC South,10,NaN
11,12,Pittsburgh Steelers,"1,208",628,558,22,0.529,1933,AFC North,11,NaN
12,13,Kansas City Chiefs,900,469,419,12,0.528,1960,AFC West,12,NaN
13,14,Oakland Raiders,900,466,423,11,0.524,1960,AFC West,13,NaN
14,15,Seattle Seahawks,676,344,331,1,0.510,1976,NFC West,14,NaN
15,16,Washington Redskins,"1,218",600,590,28,0.504,1932,NFC East,15,NaN
16,17,Los Angeles Chargers[d],900,447,442,11,0.503,1960,AFC West,16,NaN
17,18,Los Angeles Rams,"1,151",568,562,21,0.503,1937,NFC West,17,NaN
18,19,Carolina Panthers,384,190,193,1,0.496,1995,NFC South,18,NaN
19,20,Philadelphia Eagles,"1,204",577,601,26,0.490,1933,NFC East,19,NaN
20,21,Cleveland Browns,970,469,490,11,0.489,1950,AFC North,20,NaN
21,22,Tennessee Titans,900,431,463,6,0.482,1960,AFC South,21,NaN
22,23,Buffalo Bills,900,415,477,8,0.466,1960,AFC East,22,NaN
23,24,Detroit Lions,"1,249",559,658,32,0.460,1930,NFC North,23,NaN
24,25,Cincinnati Bengals,788,357,427,4,0.456,1968,AFC North,24,NaN
25,26,New Orleans Saints,802,362,435,5,0.454,1967,NFC South,25,NaN
26,27,New York Jets,900,401,491,8,0.450,1960,AFC East,26,NaN
27,28,Houston Texans,272,121,151,0,0.445,2002,AFC South,27,NaN
28,29,Jacksonville Jaguars,384,170,214,0,0.443,1995,AFC South,28,NaN
29,30,Atlanta Falcons,816,358,452,6,0.442,1966,NFC South,29,NaN
30,31,Arizona Cardinals,"1,346",553,753,40,0.426,1920,NFC West,30,NaN
31,32,Tampa Bay Buccaneers,676,260,415,1,0.385,1976,NFC South,31,NaN

In [2]:
data = {'City':['SF','LA','NYC'],'Population':[800000,3000000,8000000]}

In [5]:
city_frame = DataFrame(data)

In [6]:
city_frame

  City  Population
0   SF      800000
1   LA     3000000
2  NYC     8000000